### ISSUE TITLE
Vignette

### ISSUE THREAD

**Issue by antagomir** [rOpenGov/hansard#4]
The vignette does not work in the way described in README:

> library(hansard)
> vignette("introduction", package = "hansard")
Warning message:
vignette ‘introduction’ not found 

I noticed that there is vignette/introduction.Rmd - it would we particularly handy to be able to browse it on-line, so whynot convert it into md file and link to that in README (as for instance ropengov/pxweb) ? The conversion could be automated with git hook for instance. Another option is html vignette (as for instance with ropengov/eurostat package). Both are relatively straightfwd to create with the already existing Rmd file.

**Comment by evanodell** [comment]
I've created an HTML vignette at vignette/introduction.html. I also used pkgdown to create a website for all the package documentation, should I set that up on ropengov.github.io? And if so, is there are particular format or template I should use?

**Comment by antagomir** [comment]
Nice ! Package websites are very useful and I very much welcome setting it up on ropengov.github.io/hansard - we do not have particular formats/templates atm due as all is driven on a voluntary basis. I would leave the final decision on the template for each package author as different packages may require different solutions. However, it could be beneficial to have some shared elements across ropengov packages/websites, and handy to share these via common templates. Suggestions for a format/template are therefore welcome if you come up with one.
